import { UserNav } from "~/components/nav";
import { ThemeProvider } from "~/components/theme-provider";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                {/* <ThemeProvider attribute="class" defaultTheme="system" enableSystem> */}
                {/* <UserNav /> */}
                {children}
                {/* </ThemeProvider> */}
            </body>
        </html>
    );
}
